### ISSUE TITLE
Install method

### ISSUE THREAD

**Issue by Kazuki-tam** [Kazuki-tam/create-pure-liquid#1]
## As is
Supports only yarn create.

## To be
Multiple packages manager support:
- npm
- yarn
- pnpm

**Comment by S-codes14** [comment]
I see that  you self-assigned this issue but I'm curious why would you want to do this, given that all packages come from npmjs.com
so yarn and pnpm calls npm's api to get the same packages

**Comment by Kazuki-tam** [comment]
@S-codes14 
I want to make this CLI run the install command by each npm, yarn and pnpm.

```ts
const installCommand = `cd ${projectName} && yarn install`;
```
https://github.com/Kazuki-tam/create-pure-liquid/blob/main/src/bin/cli.ts

**Comment by S-codes14** [comment]
I think I have something in mind but I feel like I am not understanding your issue,
So to achieve this you first need to ask the use which option they want to use 
then delete yarn.lock file then install

I'm really not understanding the issue but in the meantime I'm going to fork and maybe pull request my solution
If I am misunderstanding the issue, please let me know

**Comment by S-codes14** [comment]
@Kazuki-tam  what do you think of the code commented, of course its not perfect but is this what you are trying to do

**Comment by S-codes14** [comment]
did you know that you can run the command below and it would do the same thing as yarn create
`npx create-pure-liquid <YOUR-PROJECT-NAME>`

and if solution 1 of my code above is uncommented, users without yarn can run:
`npx create-pure-liquid <YOUR-PROJECT-NAME> npm`

**Comment by Kazuki-tam** [comment]
@S-codes14 
Thank you for your advice!!
I knew the 'npx' command is same as 'yarn create'.

solution 2 sounds good to me.
// solution 2 is to actually ask the user what package manager they want to use where users type in npm or yarn or pnpm but the default will be yarn e.g

**Comment by S-codes14** [comment]
I'm about to send in my pull request still testing

**Comment by Kazuki-tam** [comment]
@S-codes14 
Thank you for your pull request!!
I merged your brunch once and changed some lines.

https://github.com/Kazuki-tam/create-pure-liquid/pull/4#issue-1404940082
